In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import numpy as np
import pandas as pd
import random
import sklearn
import time
import math
#import matplotlib.pyplot as plt
#import os
import sys
import wandb
import yaml

from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm import tqdm
from scipy import stats
#from torchviz import make_dot
from utils import *
from models import *

In [6]:
input_dim = 6
output_dim = 7

device = torch.device('cpu')
robot_choice = "7DoF-7R-Panda"
num_blocks = 5
neurons = 1024
batch_size = 100000
optimizer_choice = "Adam"
loss_choice = "lq"
experiment_number = 1
scale = 10
save_layers_str = "blocks_"+ str(num_blocks)
dataset_samples = 1000000
network_type = "DenseMLP2"
save_path = "results/"+robot_choice+"/"+network_type+"_"+robot_choice+"_" \
                + save_layers_str + "_neurons_" + str(neurons) + "_batch_" + str(batch_size)  +"_" \
                +optimizer_choice+"_"+loss_choice+"_"+str(experiment_number)+'_qlim_scale_'+str(int(scale))+'_samples_'+str(dataset_samples)
    
    
print(save_path) 
    

results/7DoF-7R-Panda/DenseMLP_7DoF-7R-Panda_blocks_5_neurons_1024_batch_100000_Adam_lq_1_qlim_scale_10_samples_1000000


In [11]:
 print("\n\n==>Testing the trained model ...\n\n")
#test_data_loader = load_test_dataset(X_test, y_test, device)
weights_file = save_path+"/best_epoch.pth"
if network_type == "MLP":
    model = MLP(input_dim, hidden_layer_sizes, output_dim).to(device)
    #model = MLP(mapping_size*2, hidden_layer_sizes, output_dim).to(device)
elif network_type == "ResMLP":
    model = ResMLPSum(input_dim, neurons, output_dim, num_blocks).to(device)
elif network_type == "DenseMLP2":
    model = DenseMLP2(input_dim, neurons, output_dim, num_blocks).to(device)

state_dict = model.state_dict()
for n, p in torch.load(weights_file, map_location=lambda storage, loc: storage).items():
    print(n)
    print(p)
    print()
    """
    if n in state_dict.keys():
        state_dict[n].copy_(p)
    else:
        raise KeyError(n)
    """



==>Testing the trained model ...


input.weight
tensor([[-0.0034,  0.2193, -0.3368, -0.3056, -0.1578,  0.1087],
        [-0.0092,  0.3247, -0.0363,  0.1098, -0.1239, -0.0808],
        [-0.3930, -0.2726, -0.1682,  0.0146,  0.1629,  0.2491],
        ...,
        [-0.3740, -0.1003,  0.0625,  0.2287, -0.2377, -0.2510],
        [ 0.1838, -0.2463, -0.1619, -0.4117, -0.0978, -0.3264],
        [ 0.0647,  0.3311,  0.1805, -0.3430,  0.3677, -0.3668]])

input.bias
tensor([-0.1581,  0.2294,  0.1933,  ..., -0.1717,  0.3562,  0.0855])

fc.weight
tensor([[-0.0272, -0.0010,  0.0083,  ...,  0.0181,  0.0059,  0.0030],
        [-0.0017,  0.0141,  0.0029,  ...,  0.0308,  0.0065, -0.0048],
        [-0.0114, -0.0020, -0.0139,  ...,  0.0028,  0.0256,  0.0277],
        ...,
        [-0.0302, -0.0088,  0.0092,  ...,  0.0067, -0.0007,  0.0108],
        [ 0.0091, -0.0081,  0.0104,  ...,  0.0117,  0.0137, -0.0173],
        [-0.0120, -0.0249,  0.0217,  ...,  0.0282,  0.0257, -0.0108]])

fc.bias
tensor([-0.0197, 

In [9]:
print(state_dict.keys())

odict_keys(['input.weight', 'input.bias', 'fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias', 'fc4.weight', 'fc4.bias', 'transition.weight', 'transition.bias', 'out.weight', 'out.bias'])
